version: "3.9"

services:
  db:
    image: postgres:16
    container_name: tripmate-postgres
    environment:
      POSTGRES_USER: tripmate
      POSTGRES_PASSWORD: supersecret
      POSTGRES_DB: tripmate
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 5s
      timeout: 5s
      retries: 10

  pgadmin:
    image: dpage/pgadmin4:8
    container_name: tripmate-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - db


volumes:
  db_data:
  
